### ISSUE TITLE
Having trouble using with React

### ISSUE THREAD

**Issue by mazhar-kv** [released-software/documentation#3]
Is there any documentation where i can use it with react.

**Comment by stefansaasen** [comment]
Could you please elaborate what you are trying to do? Are you trying to use the Released embed in a React component?

Here is a basic example that might help: https://codepen.io/ohoj/pen/bGyWMrY

**Comment by stefansaasen** [comment]
I'm assuming you found a way to use Released with React. I'm going to close this issue. Please let me know if there is anything we can do for you.
